args:
  model_name: "meta-llama/Llama-3.2-1B-Instruct"
  num_epochs: 1 
  num_batches: 4
  batch_size: 4
  forget_dataset_list:
    - "bio-forget-corpus.jsonl"
  retain_dataset_list: 
    - "wikitext"
  learning_rate: 5e-5
  steering_coefficient: 53.4
  alpha: 1883.2
  forget_layer_id: 6
  optimizer_param_layer_id: 
    - 3
  update_layer_ids:
    - 4
    - 5
    - 6
  updated_model_path: "models/"
  seed: 42
