args:
  model_name: "01-ai/Yi-34B-Chat"
  num_epochs: 1 
  num_batches: 400
  batch_size: 2
  forget_dataset_list:
    - "cyber-forget-corpus.jsonl"
    - "bio-forget-corpus.jsonl"
  retain_dataset_list:
    - "wikitext"
  learning_rate: 5e-5
  steering_coefficient: 300.0
  alpha: 350.0
  forget_layer_id: 15
  optimizer_param_layer_id: 
    - 6
  update_layer_ids:
    - 13
    - 14
    - 15
  updated_model_path: "models/"